<template><h1 id="faqs" tabindex="-1"><a class="header-anchor" href="#faqs" aria-hidden="true">#</a> FAQs</h1>
<h2 id="_1-how-much-does-hello-cost" tabindex="-1"><a class="header-anchor" href="#_1-how-much-does-hello-cost" aria-hidden="true">#</a> <em>1. How much does Hellō cost?</em></h2>
<p>Hellō is currently free, and will continue to be free until the co-operative decides Hellō has reached a critical mass of adoption. Early adopters of Hellō will be rewarded to minimize or eliminate paying for Hellō in the future.</p>
<h2 id="_2-how-much-will-hello-cost-in-the-future" tabindex="-1"><a class="header-anchor" href="#_2-how-much-will-hello-cost-in-the-future" aria-hidden="true">#</a> <em>2. How much will Hellō cost in the future?</em></h2>
<p>Hellō's business model is to charge developers an interchange fee of a few pennies for each new verified claim a user releases to an application. Hellō will not charge for log in or for active users. As Hellō starts to generate revenue in excess of expenses, Hellō will lower its fees.</p>
<h2 id="_3-how-do-i-get-started-using-hello" tabindex="-1"><a class="header-anchor" href="#_3-how-do-i-get-started-using-hello" aria-hidden="true">#</a> <em>3. How do I get started using Hellō?</em></h2>
<h2 id="_4-what-types-of-applications-is-hello-suitable-for" tabindex="-1"><a class="header-anchor" href="#_4-what-types-of-applications-is-hello-suitable-for" aria-hidden="true">#</a> <em>4. What types of applications is Hellō suitable for?</em></h2>
<p>Hellō is currently only suitable for new applications. Hellō is for individual users -- it not an enterprise identity solution.</p>
<h2 id="_5-why-is-hello-only-intended-for-new-applications" tabindex="-1"><a class="header-anchor" href="#_5-why-is-hello-only-intended-for-new-applications" aria-hidden="true">#</a> <em>5. Why is Hellō only intended for new applications?</em></h2>
<p>New applications have no existing user pool to integrate with. Since there is no existing investment in registration and log in, the Hellō value proposition to a new application is very strong. In the future, as Hellō starts to achieve a critical mass of users, we will provide integration features for existing (brown field) applications.</p>
<h2 id="_6-what-is-a-publisher" tabindex="-1"><a class="header-anchor" href="#_6-what-is-a-publisher" aria-hidden="true">#</a> <em>6. What is a publisher?</em></h2>
<p>A publisher allows you to have multiple apps, that all receive the same <code>sub</code> subject identifier for a given user.</p>
<h2 id="_7-what-is-the-difference-between-development-and-production-redirect-uris" tabindex="-1"><a class="header-anchor" href="#_7-what-is-the-difference-between-development-and-production-redirect-uris" aria-hidden="true">#</a> <em>7. What is the difference between development and production redirect URIs?</em></h2>
<p>Hellō will only allow a publisher's administrators, developers, and testers to access an application's development URIs. Other users will be denied access. Localhost addresses are not permitted in production URIs.</p>
</template>
