name: Generate Markdown Documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pages/docs/**'
      - 'scripts/generate-markdown.js'
      - '.github/workflows/generate-markdown.yml'

jobs:
  generate-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
        
      - name: Generate markdown from HTML
        run: node scripts/generate-markdown.js
        
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Files have changed"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi
          
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add markdown/
          git commit -m "Auto-generate markdown documentation from HTML [skip ci]"
          git push 