name: Ready for merge

on:
  workflow_dispatch: #Can manually trigger
  pull_request_target:
    types: [ opened, synchronize ] #Runs on PR creation/updation
    branches: [ main ]
    
jobs: 
  run_tests:
    uses: hellocoop/tools/.github/workflows/content-merge.yml@main
    # GitHub-Slack app sends a workflow status message with live updates to #content-updates channel