name: Sync with S3 Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs: 
  sync:
    uses: hellocoop/tools/.github/workflows/content-sync.yml@main
    # GitHub-Slack app sends a workflow status message with live updates to #content-updates channel
    with:
      STACK: WwwDevStack #make sure this is the right stack value #TBD: use env